=== emoo13/adeptus_astartes/user_schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "$id": "user.schema.json",
    "title": "Record of Users",
    "description": "This document records the details of users in Adeptus Astartes",
    "type": "object",
    "properties": {
        "user_id": {
            "description": "A unique identifier for a user",
            "type": "number"
        },
        "email": {
            "description": "Email of the user",
            "type": "string"
        },
        "first_name": {
            "description": "First name of the user",
            "type": "string"
        },
        "last_name": {
            "description": "Last name of the user",
            "type": "string"
        },
        "username": {
            "description": "Web username of the user",
            "type": "string"
        },
        "faction": {
            "description": "Faction chosen by the user",
            "type": "string"
        },
        "password": {
            "description": "Password of the user",
            "type": "string"
        },
        "email_verified": {
            "description": "If user has verified their email",
            "type": "boolean"
        },
        "last_ip": {
            "description": "IP of the user's last login",
            "type": "string"
        },
        "posts": {
            "description": "Post ID's relevant to user",
            "type": "object",
            "properties": {
                "discussions": {
                    "type": "array",
                    "items": {
                        "description": "List of discussion post ID's",
                        "type": "number"
                    }
                },
                "social": {
                    "type": "array",
                    "items": {
                        "description": "List of social post ID's",
                        "type": "number"
                    }
                }
            }
        }
    }
}

=== emoo13/adeptus_astartes/users.json
[
    {
        "user_id": 1,
        "email": "fake@fake.com",
        "first_name": "George",
        "last_name": "Doe",
        "username": "FlamesOfSacrifice",
        "faction": "DeathGuard",
        "password": "password1234",
        "email_verified": true,
        "last_ip": "1234.123.23",
        "posts": {
            "discussions": [
                1, 10010
            ],
            "social": [
                2, 20020
            ]
        }
    },
    {
        "user_id": 2,
        "email": "fake2@fake.com",
        "first_name": "Jake",
        "last_name": "Doe",
        "username": "PutridWarlord",
        "faction": "Salamanders",
        "password": "password56789",
        "email_verified": true,
        "last_ip": "1234.123.23",
        "posts": {
            "discussions": [
            ],
            "social": [
                3, 30020
            ]
        }
    },
    {
        "user_id": 3,
        "email": "fake3@fake.com",
        "first_name": "Sally",
        "last_name": "Doe",
        "username": "CoraxsChosen",
        "faction": "RavenGuard",
        "password": "password234",
        "email_verified": false,
        "last_ip": "1234.123.23",
        "posts": {
            "discussions": [
                949392
            ],
            "social": [
                4, 40020
            ]
        }
    },
    {
        "user_id": 4,
        "email": "fake4@fake.com",
        "first_name": "Jane",
        "last_name": "Doe",
        "username": "FulgrimsGlory",
        "faction": "Emperor's Child",
        "password": "password35465",
        "email_verified": true,
        "last_ip": "1234.123.23",
        "posts": {
            "discussions": [
                24, 893, 209184
            ],
            "social": [
                5
            ]
        }
    }
]
